version: "3.9"

x-common-variables: &common-variables
  DJANGO_SECRET_KEY:
  DEBUG:
  PUBLIC_HOST:
  DATABASE_ENGINE: django.db.backends.postgresql
  DATABASE_NAME: ruscord
  DATABASE_USER: ruscord
  DATABASE_PASSWORD: ruscord
  DATABASE_HOST: postgres
  DATABASE_PORT: 5432
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_DB: 0
  LIVEKIT_API_KEY: devkey
  LIVEKIT_API_SECRET: secret
  STATIC_ROOT: /app/static
  MEDIA_ROOT: /app/media
  MEDIA_URL:

services:
  app:
    build: .
    env_file: .env
    environment: *common-variables
    volumes:
      - media:/app/media
    depends_on:
      - postgres
      - redis
      - migration
      - livekit

  collectstatic:
    build: .
    user: root
    env_file: .env
    environment: *common-variables
    volumes:
      - static:/app/static
    command: ["django-admin", "collectstatic", "--no-input"]

  migration:
    build: .
    env_file: .env
    environment: *common-variables
    command: ["django-admin", "migrate", "--no-input"]
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ruscord
      POSTGRES_PASSWORD: ruscord
      POSTGRES_DB: ruscord
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  livekit:
    image: livekit/livekit-server:latest
    command: --config /livekit.yaml
    volumes:
      - ./livekit.yaml:/livekit.yaml
    ports:
      - "7880:7880"               # HTTP API
      - "7881:7881"               # WebSocket
      - "50000-60000:50000-60000/udp"  # RTP Media UDP Ports

  frontend:
    build: ../ruscord-fe
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - "80:80"
    depends_on:
      - collectstatic
      - app

volumes:
  postgres_data:
  redis_data:
  static:
  media:
